version: '3.8'

services:
  back:
    container_name:
      back
    build:
      context: ../Back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: unless-stopped
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5000:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data/ --console-address ":9001"
    ports:
      - "${NGINX_NETWORK_MINIO_S3_PORT}:${NGINX_NETWORK_MINIO_S3_PORT}"
      - "${NGINX_NETWORK_MINIO_CONSOLE_PORT}:${NGINX_NETWORK_MINIO_CONSOLE_PORT}"
    expose:
      - ${NGINX_NETWORK_MINIO_S3_PORT}
      - ${NGINX_NETWORK_MINIO_CONSOLE_PORT}
    volumes:
      - minio-storage:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: '${MINIO_ACCESS_KEY}'
      MINIO_ROOT_PASSWORD: '${MINIO_SECRET_KEY}'
      MINIO_BROWSER_REDIRECT_URL: http://localhost/u0C56Q-console/

  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./modules/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./modules/nginx/ssl:/etc/nginx/ssl
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - back

  odfe-node:
    image: elasticsearch:7.10.1
    container_name: odfe-node
    environment:
      - discovery.type=single-node
      - node.name=odfe-node
      - discovery.seed_hosts=odfe-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./modules/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    expose:
      - 9200
      - 9600

#  kibana:
#    image: kibana:7.10.1
#    container_name: odfe-kibana
#    ports:
#      - "5601:5601"
#    expose:
#      - "5601"
#    environment:
#      ELASTICSEARCH_URL: http://odfe-node:9200
#      ELASTICSEARCH_HOSTS: http://odfe-node:9200

  logstash:
    user: root
    image: docker.elastic.co/logstash/logstash-oss:7.9.1
    ports:
      - "5044:5044"
    expose:
      - 5044
    depends_on:
      - postgres
      - odfe-node
    environment:
      - PIPELINE_WORKERS=1
      - PIPELINE_BATCH_SIZE=125
      - PIPELINE_BATCH_DELAY=50
    volumes:
      - ./modules/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./modules/logstash/logstash_data:/usr/share/logstash/data
      - ./modules/logstash/postgresql-42.7.4.jar:/usr/share/logstash/postgresql-42.7.4.jar


volumes:
  postgres_data:
  minio-storage: