version: '3.8'

services:
  back:
    build:
      context: ../Back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres

  front:
    build:
      context: ../Front/front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: everylab-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./modules/nginx
      dockerfile: Dockerfile
    volumes:
      - ./modules/nginx/ssl:/etc/nginx/ssl
    env_file:
      - .env
    ports:
      - "80:80"           # Открываем порт 80 для HTTP
      - "443:443"         # Открываем порт 443 для HTTPS
    depends_on:
      - back

  certbot:
    image: certbot/certbot
    volumes:
      - ./modules/nginx/ssl:/etc/letsencrypt  # Храним сертификаты в одном месте с NGINX
      - ./modules/nginx/ssl-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"


volumes:
  postgres_data: