name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Install dependencies
        working-directory: modules/prisma
        run: npm install

      - name: Load environment variables and run scripts
        working-directory: modules/prisma
        run: |
          set -a
          source .env
          set +a
          npm run generate
          npm run deploy:prisma

      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@89.169.38.6 << 'EOF'
          cd ~/everylab/Server
          git pull origin main
          docker-compose up -d --build
          EOF